apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: m802nqqy6-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/m802nqqy6-dotnet-basic-gitops