apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m802nqqy6-dotnet-basic
  janus-idp.io/tekton: m802nqqy6-dotnet-basic
  backstage.io/kubernetes-id: m802nqqy6-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: m802nqqy6-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
